[package]
name = "cargo-single-pyo3"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"

[dependencies]
clap = "2.33"
anyhow = "1.0"
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}